-- Create user and grant privileges

SELECT USERNAME FROM DBA_USERS;

-- Create user in CDB
ALTER SESSION SET CONTAINER = CDB$ROOT;
SHOW CON_NAME;

DROP USER c##username CASCADE;
CREATE USER c##username IDENTIFIED BY parola24;
SELECT USERNAME FROM DBA_USERS;

GRANT CREATE SESSION TO c##username;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO c##username;
GRANT UNLIMITED TABLESPACE TO c##username;

-- Create user in PDB
SHOW PDBS;
ALTER SESSION SET CONTAINER = XEPDB1;
SHOW CON_NAME;

DROP USER username CASCADE;
CREATE USER username IDENTIFIED BY parola24;
SELECT USERNAME FROM DBA_USERS;

GRANT CREATE SESSION TO username;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO username;
GRANT UNLIMITED TABLESPACE TO username;

-- Create and Insert data into tables

DROP TABLE ENROLLMENTS CASCADE CONSTRAINTS;
DROP TABLE COURSE_TEACHERS CASCADE CONSTRAINTS;
DROP TABLE STUDENTS CASCADE CONSTRAINTS;
DROP TABLE COURSES CASCADE CONSTRAINTS;
DROP TABLE TEACHERS CASCADE CONSTRAINTS;

DROP SEQUENCE STUDENT_SEQ;
DROP SEQUENCE COURSES_SEQ;
DROP SEQUENCE TEACHERS_SEQ;
DROP SEQUENCE ENROLLMENTS_SEQ;
DROP SEQUENCE COURSE_TEACHERS_SEQ;

CREATE SEQUENCE STUDENT_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 999999
  CACHE 20;

CREATE TABLE STUDENTS (
    student_id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(100),
    date_of_birth DATE
);

INSERT INTO STUDENTS VALUES (STUDENT_SEQ.NEXTVAL, 'Ion', 'Popescu', 'ion.popescu@example.com', TO_DATE('2000-05-15', 'YYYY-MM-DD'));
INSERT INTO STUDENTS VALUES (STUDENT_SEQ.NEXTVAL, 'Maria', 'Ionescu', 'maria.ionescu@example.com', TO_DATE('1999-11-23', 'YYYY-MM-DD'));
INSERT INTO STUDENTS VALUES (STUDENT_SEQ.NEXTVAL, 'Andrei', 'Vasilescu', 'andrei.vasilescu@example.com', TO_DATE('2001-03-10', 'YYYY-MM-DD'));
INSERT INTO STUDENTS VALUES (STUDENT_SEQ.NEXTVAL, 'Elena', 'Dumitru', 'elena.dumitru@example.com', TO_DATE('2002-07-29', 'YYYY-MM-DD'));
INSERT INTO STUDENTS VALUES (STUDENT_SEQ.NEXTVAL, 'Ion', 'Ionescu', 'ion.ionescu@example.com', TO_DATE('2000-10-12', 'YYYY-MM-DD'));
INSERT INTO STUDENTS VALUES (STUDENT_SEQ.NEXTVAL, 'Ana', 'Popescu', 'ana.popescu@example.com', TO_DATE('2001-04-22', 'YYYY-MM-DD'));
INSERT INTO STUDENTS VALUES (STUDENT_SEQ.NEXTVAL, 'Alex', 'Dumitru', 'alex.dumitru@example.com', TO_DATE('1998-12-01', 'YYYY-MM-DD'));
INSERT INTO STUDENTS VALUES (STUDENT_SEQ.NEXTVAL, 'Maria', 'Dumitrescu', 'maria.dumitrescu@example.com', TO_DATE('2002-06-17', 'YYYY-MM-DD'));
INSERT INTO STUDENTS VALUES (STUDENT_SEQ.NEXTVAL, 'Ion', 'Vasilescu', 'ion.vasilescu@example.com', TO_DATE('2001-09-05', 'YYYY-MM-DD'));
INSERT INTO STUDENTS VALUES (STUDENT_SEQ.NEXTVAL, 'Elena', 'Popa', 'elena.popa@example.com', TO_DATE('2000-08-30', 'YYYY-MM-DD'));

CREATE SEQUENCE COURSES_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 999999
  CACHE 20;

CREATE TABLE COURSES (
    course_id NUMBER PRIMARY KEY,
    course_name VARCHAR2(100),
    course_description VARCHAR2(255)
);

INSERT INTO COURSES VALUES (COURSES_SEQ.NEXTVAL, 'Baze de Date', 'Introducere in conceptele de baze de date');
INSERT INTO COURSES VALUES (COURSES_SEQ.NEXTVAL, 'Programare Java', 'Incepator si intermediar Java');
INSERT INTO COURSES VALUES (COURSES_SEQ.NEXTVAL, 'Analiza de Date', 'Curs avansat de analiza si vizualizare date');
INSERT INTO COURSES VALUES (COURSES_SEQ.NEXTVAL, 'Matematica Aplicata', 'Matematica pentru stiinta calculatoarelor');
INSERT INTO COURSES VALUES (COURSES_SEQ.NEXTVAL, 'Python Programming', 'Introduction to Python for beginners');
INSERT INTO COURSES VALUES (COURSES_SEQ.NEXTVAL, 'Machine Learning', 'Advanced concepts in machine learning');
INSERT INTO COURSES VALUES (COURSES_SEQ.NEXTVAL, 'Computer Networks', 'Fundamentals of networking and communication');
INSERT INTO COURSES VALUES (COURSES_SEQ.NEXTVAL, 'Cyber Security', 'Introduction to cyber security principles');

CREATE SEQUENCE TEACHERS_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 999999
  CACHE 20;

CREATE TABLE TEACHERS (
    teacher_id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(100)
);

INSERT INTO TEACHERS VALUES (TEACHERS_SEQ.NEXTVAL, 'Adrian', 'Constantinescu', 'adrian.constantinescu@example.com');
INSERT INTO TEACHERS VALUES (TEACHERS_SEQ.NEXTVAL, 'Raluca', 'Georgescu', 'raluca.georgescu@example.com');
INSERT INTO TEACHERS VALUES (TEACHERS_SEQ.NEXTVAL, 'cristian', 'Badea', 'cristian.badea@example.com');
INSERT INTO TEACHERS VALUES (TEACHERS_SEQ.NEXTVAL, 'Ioana', 'Petrescu', 'ioana.petrescu@example.com');
INSERT INTO TEACHERS VALUES (TEACHERS_SEQ.NEXTVAL, 'George', 'Popescu', 'george.popescu@example.com');
INSERT INTO TEACHERS VALUES (TEACHERS_SEQ.NEXTVAL, 'Anca', 'Ionescu', 'anca.ionescu@example.com');
INSERT INTO TEACHERS VALUES (TEACHERS_SEQ.NEXTVAL, 'Mihai', 'Dumitru', 'mihai.dumitru@example.com');
INSERT INTO TEACHERS VALUES (TEACHERS_SEQ.NEXTVAL, 'Ioana', 'Vasilescu', 'ioana.vasilescu@example.com');

CREATE SEQUENCE ENROLLMENTS_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 999999
  CACHE 20;

CREATE TABLE ENROLLMENTS (
    CONSTRAINT enrollments_id PRIMARY KEY (student_id, course_id),
    student_id NUMBER,
    course_id NUMBER,
    enrollment_date DATE,
    CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES STUDENTS(student_id),
    CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES COURSES(course_id)
);

INSERT INTO ENROLLMENTS VALUES (1, 1, TO_DATE('2023-09-01', 'YYYY-MM-DD'));
INSERT INTO ENROLLMENTS VALUES (1, 2, TO_DATE('2023-09-01', 'YYYY-MM-DD'));
INSERT INTO ENROLLMENTS VALUES (2, 1, TO_DATE('2023-09-05', 'YYYY-MM-DD'));
INSERT INTO ENROLLMENTS VALUES (3, 3, TO_DATE('2023-09-10', 'YYYY-MM-DD'));
INSERT INTO ENROLLMENTS VALUES (4, 4, TO_DATE('2023-09-15', 'YYYY-MM-DD'));
INSERT INTO ENROLLMENTS VALUES (5, 2, TO_DATE('2023-10-01', 'YYYY-MM-DD'));
INSERT INTO ENROLLMENTS VALUES (6, 1, TO_DATE('2023-10-01', 'YYYY-MM-DD'));
INSERT INTO ENROLLMENTS VALUES (7, 5, TO_DATE('2023-10-02', 'YYYY-MM-DD'));
INSERT INTO ENROLLMENTS VALUES (8, 6, TO_DATE('2023-10-03', 'YYYY-MM-DD'));
INSERT INTO ENROLLMENTS VALUES (9, 3, TO_DATE('2023-10-04', 'YYYY-MM-DD'));
INSERT INTO ENROLLMENTS VALUES (10, 4, TO_DATE('2023-10-05', 'YYYY-MM-DD'));
INSERT INTO ENROLLMENTS VALUES (1, 5, TO_DATE('2023-10-06', 'YYYY-MM-DD'));
INSERT INTO ENROLLMENTS VALUES (2, 6, TO_DATE('2023-10-07', 'YYYY-MM-DD'));

CREATE SEQUENCE COURSE_TEACHERS_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 999999
  CACHE 20;

CREATE TABLE COURSE_TEACHERS (
    CONSTRAINT course_teacher_id PRIMARY KEY (course_id, teacher_id),
    course_id NUMBER,
    teacher_id NUMBER,
    assigned_date DATE,
    FOREIGN KEY (course_id) REFERENCES COURSES(course_id),
    FOREIGN KEY (teacher_id) REFERENCES TEACHERS(teacher_id)
);

INSERT INTO COURSE_TEACHERS VALUES (1, 1, TO_DATE('2023-08-25', 'YYYY-MM-DD'));
INSERT INTO COURSE_TEACHERS VALUES (2, 2, TO_DATE('2023-08-26', 'YYYY-MM-DD'));
INSERT INTO COURSE_TEACHERS VALUES (3, 3, TO_DATE('2023-08-27', 'YYYY-MM-DD'));
INSERT INTO COURSE_TEACHERS VALUES (4, 4, TO_DATE('2023-08-28', 'YYYY-MM-DD'));
INSERT INTO COURSE_TEACHERS VALUES (5, 5, TO_DATE('2023-09-01', 'YYYY-MM-DD'));
INSERT INTO COURSE_TEACHERS VALUES (6, 6, TO_DATE('2023-09-02', 'YYYY-MM-DD'));
INSERT INTO COURSE_TEACHERS VALUES (7, 7, TO_DATE('2023-09-03', 'YYYY-MM-DD'));
INSERT INTO COURSE_TEACHERS VALUES (8, 8, TO_DATE('2023-09-04', 'YYYY-MM-DD'));
INSERT INTO COURSE_TEACHERS VALUES (2, 7, TO_DATE('2023-09-05', 'YYYY-MM-DD'));
INSERT INTO COURSE_TEACHERS VALUES (4, 6, TO_DATE('2023-09-06', 'YYYY-MM-DD'));
INSERT INTO COURSE_TEACHERS VALUES (3, 5, TO_DATE('2023-09-07', 'YYYY-MM-DD'));
INSERT INTO COURSE_TEACHERS VALUES (1, 8, TO_DATE('2023-09-08', 'YYYY-MM-DD'));
